import { StyleSheet, Dimensions } from 'react-native';
import { BaseColors, FontFamily } from '@config/theme';

export default StyleSheet.create({
  container: {
    // paddingHorizontal: 10,
    backgroundColor: BaseColors.white,
    height: Dimensions.get('window').height,
  },
  btnView: {
    paddingHorizontal: 20,
    width: '100%',
    position: 'absolute',
    bottom: Dimensions.get('window').height / 20,
    alignSelf: 'center',
  },
  mapStyle: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  descriptionTxt: {},
  mainView: {
    width: '90%',
    alignSelf: 'center',
  },
  TextInp1: {
    alignSelf: 'center',
    color: BaseColors.black,
    borderRadius: 8,
    borderColor: BaseColors.borderColor,
    borderWidth: 1,
    marginBottom: 0,
  },
  titleText: {
    color: 'black',
    paddingBottom: 5,
    fontFamily: FontFamily.regular,
  },
  errorTxt: {
    color: '#FF0B1E',
    paddingLeft: 5,
    paddingBottom: 10,
  },
  textInp4: {
    height: 90,
    alignSelf: 'center',
    color: BaseColors.black,
    borderRadius: 8,
    borderColor: BaseColors.borderColor,
    borderWidth: 1,
    marginBottom: 0,
  },
  dateInput: {
    borderWidth: 1,
    borderColor: BaseColors.borderColor,
    height: 50,
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderRadius: 8,
  },
  radioview: {
    display: 'flex',
    flexDirection: 'row',
    marginVertical: 5,
  },
  radText1: {
    color: '#585858',
    alignSelf: 'center',
    fontSize: 16,
    fontFamily: FontFamily.bold,
  },
  datePickerStyle: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  markerImage: {
    width: 40,
    height: 40,
    padding: 2,
    borderWidth: 1,
    borderRadius: 50,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: BaseColors.primary,
    backgroundColor: BaseColors.white,
    overflow: 'hidden',
    zIndex: 1,
  },
  triangle: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 50,
    borderRightWidth: 50,
    borderBottomWidth: 100,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'red',
    position: 'absolute',
    transform: [{ rotate: '180deg' }],
    top: 10,
  },
  imgmain: {
    width: 35,
    height: 35,
    borderRadius: 50,
  },
  buttonStyle: {
    borderWidth: 1,
    borderColor: BaseColors.primary,
    borderRadius: 8,
    flex: 1,
    alignItems: 'center',
    padding: 10,
    margin: 2,
  },
  btnContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  modalContainer: {
    width: '90%',
    backgroundColor: BaseColors.white,
    borderRadius: 20,
    margin: 20,
    elevation: 20,
    overflow: 'hidden',
  },
  modalView: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
