import { StyleSheet, Dimensions } from 'react-native';
import { BaseColors, FontFamily } from '@config/theme';
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BaseColors.white,
    height: Dimensions.get('window').height,
  },
  firstView: {
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  userImg: {
    alignSelf: 'center',
    width: '100%',
    height: Dimensions.get('window').height / 4,
    borderRadius: 10,
  },
  menuIconView: {
    position: 'absolute',
    flexDirection: 'row',
    left: 20,
    top: Dimensions.get('window').height / 22,
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 20,
    backgroundColor: BaseColors.white,
  },
  HeaderRowView: {
    paddingVertical: 8,
    paddingHorizontal: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileImg: {
    width: 40,
    height: 40,
    borderRadius: 40,
  },
  userName: {
    paddingLeft: 5,
    fontSize: 14,
    color: BaseColors.black,
    fontWeight: 'bold',
  },
  Host: {
    fontSize: 12,
    paddingLeft: 5,
    color: BaseColors.black,
  },
  imgsView: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  imgOne: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: BaseColors.white,
  },
  addPerson: {
    color: BaseColors.white,
    fontFamily: FontFamily.bold,
    fontSize: 12,
    textAlign: 'center',
  },
  locationTxt: {
    fontSize: 10,
    color: BaseColors.black,
  },
  rowView: {
    paddingVertical: 5,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addIcon: {
    opacity: 0.7,
  },
  details: {
    paddingHorizontal: 5,
    flexDirection: 'row',
    fontSize: 14,
    color: BaseColors.lightBlack,
    fontFamily: FontFamily.regular,
  },
  dateTime: {
    paddingHorizontal: 5,
    flexDirection: 'row',
    fontSize: 14,
    color: BaseColors.lightBlack,
  },
  btnsView: {
    flexDirection: 'row',
    paddingVertical: 10,
  },
  btnTxtView: {
    alignItems: 'center',
    alignSelf: 'center',
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    marginHorizontal: 5,
  },
  btnTxt: {
    fontSize: 14,
    fontFamily: FontFamily.regular,
    color: BaseColors.primary,
  },
  commentsTxt: {
    marginTop: 50,
    fontSize: 16,
    color: BaseColors.lightBlack,
    fontFamily: FontFamily.bold,
  },
  searchSection: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 5,
  },
  input: {
    flex: 1,
    color: BaseColors.white,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: BaseColors.borderColor,
    borderRadius: 8,
    marginLeft: 15,
    alignItems: 'center',
    paddingRight: 4,
    height: 50,
  },
  sendIcon: {
    backgroundColor: BaseColors.lightRed,
    padding: 10,
    borderRadius: 6,
    alignSelf: 'flex-end',
    alignItems: 'center',
    margin: 0,
    justifyContent: 'center',
  },
  btnView: {
    paddingHorizontal: 20,
    width: '100%',
    position: 'absolute',
    bottom: Dimensions.get('window').height / 35,
    alignSelf: 'center',
  },

  btnView1: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 40,
    marginTop: 15
  },
  btnOne: {
    flex: 1,
    height: 50,
    paddingHorizontal: 5
  },
  pinIcon: {
    opacity: 0.3,
  },
  txtShowMore: {
    fontSize: 14,
    color: BaseColors.primary,
    fontFamily: FontFamily.regular,
  },
  paidSheetImgview: {
    position: 'absolute',
    width: '100%',
  },
  paidImg: {
    top: 22,
    position: 'absolute',
    color: 'white',
    backgroundColor: BaseColors.primary,
    left: -60,
    paddingVertical: 5,
    width: '50%',
    textAlign: 'center',
    transform: [{ rotate: '-45deg' }],
  },
  editImgStyle: {
    position: 'absolute',
    right: 14,
    top: 10,
    height: 30,
    width: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: BaseColors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 6,
  },
});
