import { StyleSheet, Dimensions } from 'react-native';
import { BaseColors, FontFamily } from '@config/theme';

export default StyleSheet.create({
  container: {
    paddingVertical: 20,
    paddingTop: 100,
    backgroundColor: BaseColors.white,
  },
  firstView: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 0.8,
    borderBottomColor: BaseColors.borderColor,
  },
  IconrowView: {
    paddingVertical: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  nameTxt: {
    color: BaseColors.lightBlack,
    fontFamily: FontFamily.bold,
    fontWeight: '900',
    fontSize: 16,
  },
  scrollView: {
    marginHorizontal: 20,
  },
  text: {
    fontSize: 30,
  },
  action: {
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 25,
    padding: 15,
    position: 'absolute',
    bottom: 5,
    backgroundColor: '#000',
    width: '50%',
    justifyContent: 'space-around',
  },
  actionItem: {
    color: '#fff',
  },
  frindesName: {
    fontSize: 14,
    marginTop: 6,
  },
  details: {
    paddingHorizontal: 10,
    flexDirection: 'row',
    fontSize: 14,
    fontFamily: FontFamily.regular,
    color: BaseColors.textGrey,
  },
  secRowView: {
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  scoll: {
    flexGrow: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  btnTxtView: {
    backgroundColor: BaseColors.lightRed,
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 8,
    marginVertical: 5,
    marginHorizontal: 5,
  },
  headingTxt: {
    fontFamily: FontFamily.regular,
    color: BaseColors.textGrey,
    fontSize: 12,
  },
  profile: {
    width: 150,
    height: 150,
    borderWidth: 5,
    borderRadius: 150,
    borderColor: BaseColors.white,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    backgroundColor: BaseColors.borderColor,
    position: 'relative',
  },

  avatarSty: {
    width: '100%',
    height: '100%',
    borderRadius: 150,
    resizeMode: 'cover',
  },
  profileImg: {
    width: 50,
    height: 50,
    borderRadius: 50,
  },
  camBtnView: {
    position: 'absolute',
    backgroundColor: BaseColors.white,
    padding: 8,
    borderRadius: 8,
    right: 10,
    bottom: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  btnTxt: {
    fontSize: 14,
    fontFamily: FontFamily.regular,
    color: BaseColors.primary,
  },
  btnView: {
    paddingHorizontal: 20,
    width: '100%',
    backgroundColor: BaseColors.white,
    position: 'absolute',
    bottom: Dimensions.get('window').height / 100,
    alignSelf: 'center',
  },
  item: {
    backgroundColor: BaseColors.white,
    borderRadius: 20,
    borderColor: '#ddd',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    padding: 12,
    marginTop: 20,
  },
  profileTitleView: {
    flex: 1,
  },
  partyImg: {
    width: '100%',
    height: Dimensions.get('window').height / 4,
    borderRadius: 10,
  },
  menuIconView: {
    position: 'absolute',
    right: 5,
    top: 10,
    paddingVertical: 9,
    paddingHorizontal: 2,
    borderRadius: 5,
    backgroundColor: BaseColors.white,
  },
  menuIcon: {},
  rowView: {
    paddingVertical: 8,
    paddingHorizontal: 5,
    flexDirection: 'row',
    // alignItems: 'center',
  },
  imgsView: {
    flexDirection: 'row',
  },
  imgOne: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: BaseColors.white,
  },
  profileImg_2: {
    width: 40,
    height: 40,
    borderRadius: 40,
  },
  imgTwo: {
    width: 35,
    height: 35,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: BaseColors.white,
    position: 'absolute',
    left: 25,
  },
  imgThree: {
    width: 35,
    height: 35,
    backgroundColor: '#585858',
    borderRadius: 30,
    borderWidth: 2,
    borderColor: BaseColors.white,
    position: 'absolute',
    right: -35,
  },
  addPerson: {
    color: BaseColors.white,
    fontSize: 10,
    textAlign: 'center',
  },
  caption: {
    fontSize: 16,
    color: BaseColors.black,
    fontFamily: FontFamily.bold,
  },
  btnsView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  btnOne: {
    width: '48%',
  },
  bottomView: {
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  avtarView: {
    position: 'absolute',
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    bottom: Dimensions.get('window').height / 15,
  },
  modalRowView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  modelTxt: {
    textAlign: 'center',
    color: BaseColors.textGrey,
    fontSize: 16,
  },
  slideContainer: {
    paddingVertical: 15,
    borderBottomWidth: 0.8,
    borderBottomColor: BaseColors.borderColor,
  },
  slideTitleContainer: {
    marginBottom: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tabContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  partyDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  loaderView: {
    height: 300,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnView1: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  btnOne1: {
    flex: 1,
  },
  plusIcon: {
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 4,
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderColor: BaseColors.primary,
    backgroundColor: BaseColors.white,
  },
  storyTitleSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  storyTitle: {
    color: BaseColors.lightBlack,
    fontFamily: FontFamily.bold,
    fontWeight: '900',
    fontSize: 16,
    paddingLeft: 20,
  },
  addIconStyle: {
    color: BaseColors.primary,
    fontSize: 26,
    marginLeft: 8,
  },
  pitureIcon: {
    // bottom:
    // alignSelf: 'center',
    // justifyContent: 'center',
    backgroundColor: 'red',
    // position:'absolute',
    color: BaseColors.primary,
    fontSize: 26,
    // marginLeft: 8,
  },
});
